app/routes/cliente_routes.py
from flask import Blueprint, render_template, jsonify, request
from app.models.cliente import Cliente
from app import db

cliente_bp = Blueprint('cliente', __name__, url_prefix='/clientes')

@cliente_bp.route('/')
def index():
    return render_template("cliente_index.html")

@cliente_bp.route('/listar', methods=['GET'])
def listar_clientes():
    clientes = Cliente.query.all()
    clientes_dict = []
    for cliente in clientes:
        clientes_dict.append(cliente.to_dict())

    return jsonify(clientes_dict), 200

@cliente_bp.route('/cadastrar', methods=['POST'])
def cadastrar_cliente():
    data = request.get_json()

    new_cliente = Cliente(data.get('nome'), data.get('email'), data.get('telefone'))

    db.session.add(new_cliente)
    db.session.commit()

    return jsonify(new_cliente.to_dict()) , 201

@cliente_bp.route('/atualizar', methods=['PUT'])
def atualizar_cliente():
    data = request.get_json()
    id_cliente = data.get('id')
    cliente = Cliente.query.get_or_404(id_cliente)

    cliente.nome = data.get('nome')
    cliente.email = data.get('email')
    cliente.telefone = data.get('telefone')
    db.session.commit()

    return jsonify(cliente.to_dict()), 201

@cliente_bp.route('/excluir/<int:id>', methods=['DELETE'])
def excluir_cliente(id):

    cliente = Cliente.query.get_or_404(id)
    db.session.delete(cliente)
    db.session.commit()
    return jsonify({}), 200

app/routes/compra_route.py
from datetime import datetime
from app import db
from flask import Blueprint, jsonify, render_template, request
from sqlalchemy import func

from app.models import Cliente, Produto, CompraProduto
from app.models.compra import Compra

compra_bp = Blueprint('compra', __name__, url_prefix='/compras')


@compra_bp.route('/')
def index():
    return render_template("compra_index.html")


# Preciso criar rotas para registrar e consultar compras

@compra_bp.route('/cadastrar', methods=['POST'])
def registrar_compra():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({'error': 'Json inválido ou ausente'}), 400

    id_cliente = data.get('id_cliente')
    produtos = data.get('produtos')

    if not (id_cliente and produtos):
        return jsonify({'Error': 'id_cliente e produtos são obrigatórios'}), 400

    if not isinstance(produtos, list) or not produtos:
        return jsonify({'Error': 'produtos deve ser uma lista não vazia'})

    for prod in produtos:
        if not (prod.get('id_produto') and prod.get('quantidade')):
            return jsonify({'error': 'Cada produto deve ter id_produto e quantidade'}), 400
        try:
            quantidade = int(prod.get('quantidade'))
            if quantidade < 1:
                raise ValueError
        except (ValueError, TypeError):
            return jsonify(
                {'error': f'Quantidade de id_produto {prod.get("id_produto")} deve ser um inteiro positivo'}), 400

    cliente = Cliente.query.get_or_404(id_cliente)

    compra = Compra(data=datetime.utcnow(), cliente=cliente, )
    db.session.add(compra)
    db.session.commit()

    produtos_resposta = []
    for prod in produtos:
        id_produto = prod['id_produto']
        quantidade = int(prod['quantidade'])

        produto = Produto.query.get_or_404(id_produto)

        compra_produto = CompraProduto(
            compra_id=compra.id,
            produto_id=produto.id,
            quantidade=quantidade,
            valor_produto=produto.preco
        )

        db.session.add(compra_produto)

        produto_dict = produto.to_dict()
        produto_dict['quantidade'] = quantidade
        produto_dict['valor_total'] = produto.preco * quantidade
        produtos_resposta.append(produto_dict)

    db.session.commit()

    resposta = {
        'id': compra.id,
        'data': compra.data.isoformat(),
        'cliente': cliente.to_dict(),
        'produtos': produtos_resposta
    }
    return jsonify(resposta), 201


@compra_bp.route('/consulta', methods=['POST'])
def consulta_compra():
    # Obtem os dados do request
    data = request.get_json(silent=True) or {}

    # Definição dos filtros permitidos
    filtros_permitidos = {
        'id_produto': int,
        'id_compra': int,
        'id_cliente': int,
        'data_inicial': datetime,
        'data_final': datetime
    }

    # Limite máximo de itens por consulta
    MAX_ITENS = 100

    # Validação e conversão dos filtros
    filtros = {}
    try:
        for chave, type_cast in filtros_permitidos.items():
            valor = data.get(chave)
            if valor is not None:
                try:
                    if chave in ['data_inicial', 'data_final']:
                        valor_convertido = datetime.fromisoformat(valor)
                        filtros[chave] = valor_convertido
                    else:
                        # Converte para o tipo apropriado e valida
                        valor_convertido = type_cast(valor)
                        if type_cast == int and valor_convertido < 1:
                            raise ValueError
                        filtros[chave] = valor_convertido

                except (ValueError, TypeError):
                    return jsonify({'error': f'O Campo {chave} deve ser um inteiro positivo'}), 400

                # Valida se há mais de um filtro quando id_compra está presente
                if 'id_compra' in filtros and len(filtros) > 1:
                    return jsonify(
                        {'error: "Quando id_compra é especificado, nenhum outro filtro pode ser aplicado'}), 400

        # Validar se a data inicial não é maior que a final
        if 'data_inicial' in filtros and 'data_final' in filtros:
            if filtros['data_inicial'] > filtros['data_final']:
                return jsonify({'error': 'data_inicio não pode ser posterior a data_fim'}), 400

    except Exception as e:
        return jsonify({'error': 'Erro na validação dos filtros'}), 400

    try:
        # Consulta com base nos filtros
        if 'id_compra' in filtros:
            compra = Compra.query.get_or_404(filtros['id_compra'])
            return jsonify(compra.to_dict()), 200

        # Construção da query dinâmica para multiplos filtros
        query = Compra.query

        if 'id_cliente' in filtros:
            query = query.filter_by(cliente_id=filtros["id_cliente"])

        if 'id_produto' in filtros:
            compra_ids = (
                # Subquery para encontrar compras relacionadas ao produto
                CompraProduto.query
                .filter_by(produto_id=filtros['id_produto'])
                .with_entities(CompraProduto.compra_id)
                .subquery()
            )
            query = query.filter(Compra.id.in_(compra_ids))

        if 'data_inicial' in filtros:
            query = query.filter(Compra.data >= filtros['data_inicial'])
        if 'data_final' in filtros:
            query = query.filter(Compra.data <= filtros['data_final'])

        # Aplica limite de filtros
        compras = query.limit(MAX_ITENS).all()

        dict_qtn_prod = []


        # Transforma o resultado em uma lista json
        return jsonify([compra.to_dict() for compra in compras]), 200

    except Exception as e:
        return jsonify({'error': 'Erro ao processar a consulta'}), 500


@compra_bp.route('/deletar/<int:id_compra>', methods=['DELETE'])
def deletar_compra(id_compra):
    compra = Compra.query.get_or_404(id_compra)
    db.session.delete(compra)
    db.session.commit()

    return jsonify({}), 200

@compra_bp.route('/relatorio/vendas_por_produto', methods=['GET'])
def relatorio_vendas_por_produto():
    try:
        # Consulta que soma a quantidade de cada produto vendido
        resultados = (
            CompraProduto.query
            .join(Produto)
            .group_by(CompraProduto.produto_id)
            .with_entities(
                CompraProduto.produto_id,
                Produto.nome,
                func.sum(CompraProduto.quantidade).label('quantidade_total')
            )
            .all()
        )

        # Formata o resultado como um dicionário
        relatorio = [
            {
                'Produto_id': resultado.produto_id,
                'Nome': resultado.nome,
                'Quantidade_Total_Vendida': int(resultado.quantidade_total)
            }
            for resultado in resultados
        ]

        return jsonify(relatorio), 200

    except Exception as e:
        return jsonify({'error': 'Erro ao gerar relatório'}), 500

app/routes/produto_routes.py
from flask import Blueprint, jsonify, render_template, request
from app.models.produto import Produto
from app import db

produto_bp = Blueprint('produto', __name__, url_prefix='/produtos')


@produto_bp.route('/')
def index():
    return render_template("produto_index.html")


@produto_bp.route('/listar', methods=['GET'])
def listar_produtos():
    produtos = Produto.query.all()
    produtos_dict = []
    for produto in produtos:
        produtos_dict.append(produto.to_dict())

    return jsonify(produtos_dict), 200


@produto_bp.route('/cadastrar', methods=['POST'])
def cadastrar_produto():
    data = request.get_json()

    new_produto = Produto(data.get('nome'), data.get('descricao'), data.get('preco'))

    db.session.add(new_produto)
    db.session.commit()

    return jsonify(new_produto.to_dict()), 201


@produto_bp.route('/atualizar', methods=['PUT'])
def atualizar_produto():
    data = request.get_json()
    id_produto = data.get('id')
    produto = Produto.query.get_or_404(id_produto)

    produto.nome = data.get('nome')
    produto.descricao = data.get('descricao')
    produto.preco = data.get('preco')

    db.session.commit()

    return jsonify(produto.to_dict()), 201


@produto_bp.route('/excluir/<int:id>', methods=['DELETE'])
def excluir_produto(id):
    produto = Produto.query.get_or_404(id)
    db.session.delete(produto)
    db.session.commit()
    return jsonify({}), 200

app/templates/cliente_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <title>Gerenciador de Clientes</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <style>
        body {
            background-color: #f5f5f5;
            min-height: 100vh;
            padding: 1rem;
        }

        .box {
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            margin-bottom: 2rem;
        }

        .title.is-1 {
            color: #3273dc;
        }

        .table-container {
            overflow-x: auto;
        }

        .button.is-primary {
            background-color: #3273dc;
        }

        .button.is-danger {
            background-color: #ff3860;
        }

        .button.is-info {
            background-color: #23d160;
        }

        .button.is-loading::after {
            border-color: transparent transparent #fff #fff !important;
        }

        @media screen and (max-width: 768px) {
            .columns.is-mobile > .column {
                margin-bottom: 1rem;
            }
        }
    </style>
</head>
<body>
<div class="box">
    <div class="container">
        <h1 class="title is-1 has-text-centered">Clientes</h1>
        <div class="buttons is-centered">
            <button class="button is-primary is-rounded" onclick="window.location.href='http://127.0.0.1:5000/'">
                <span class="icon">
                    <i class="fas fa-arrow-left"></i>
                </span>
                <span>Voltar</span>
            </button>
        </div>

        <!-- Formulário para cadastro de Clientes -->
        <div class="box">
            <form id="form_cadastro">
                <h2 class="title is-4">Cadastrar Clientes</h2>
                <div class="field">
                    <label class="label" for="nome_cadastro">Nome</label>
                    <div class="control has-icons-left">
                        <input class="input" type="text" id="nome_cadastro" name="nome" placeholder="Digite seu nome"
                               required>
                        <span class="icon is-small is-left">
                            <i class="fas fa-user"></i>
                        </span>
                    </div>
                </div>

                <div class="field">
                    <label class="label" for="email_cadastro">Email</label>
                    <div class="control has-icons-left">
                        <input class="input" type="text" id="email_cadastro" name="email" placeholder="Digite seu email"
                               required>
                        <span class="icon is-small is-left">
                            <i class="fas fa-envelope"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="telefone_cadastro">Telefone</label>
                    <div class="control has-icons-left">
                        <input class="input" type="text" id="telefone_cadastro" name="telefone"
                               placeholder="Digite seu telefone" required>
                        <span class="icon is-small is-left">
                            <i class="fas fa-phone"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="button is-primary is-rounded" type="submit" value="Enviar" id="enviar_cadastro">
                    </div>
                </div>
            </form>
        </div>

        <!-- Tabela para listar Clientes -->
        <div class="box">
            <h2 class="title is-4">Listar Clientes</h2>
            <button class="button is-info" id="Carregar_btn" onclick="fetchData()">
                <span class="icon">
                    <i class="fas fa-list"></i>
                </span>
                <span>Listar</span>
            </button>
            <button class="button is-light" id="voltar_btn" onclick="resetTable()">
                    <span class="icon">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                <span>Voltar</span>
            </button>
            <div id="table_container" class="hidden">
                <table class="table is-striped is-hoverable is-fullwidth" id="data_table">
                    <thead>
                    <tr id="header_row"></tr>
                    </thead>
                    <tbody id="table_body"></tbody>
                </table>
            </div>
        </div>

        <!-- Form para Atualizar cadastro Clientes -->
        <div class="box">
            <form id="form_atualizar">
                <h2 class="title is-4">Atualizar Cliente</h2>
                <label class="label" for="id_atualizar">ID</label>
                <div class="control has-icons-left">
                    <input class="input" type="number" id="id_atualizar" name="id" placeholder="Digite seu ID" required>
                    <span class="icon is-small is-left">
                        <i class="fas fa-id-badge"></i>
                    </span>
                </div>
                <div class="field">
                    <label class="label" for="nome_cadastro">Nome</label>
                    <div class="control has-icons-left">
                        <input class="input" type="text" id="nome_atualizar" name="nome" placeholder="Digite seu nome"
                               required>
                        <span class="icon is-small is-left">
                            <i class="fas fa-user"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="email_cadastro">Email</label>
                    <div class="control has-icons-left">
                        <input class="input" type="text" id="email_atualizar" name="email"
                               placeholder="Digite seu email" required>
                        <span class="icon is-small is-left">
                            <i class="fas fa-envelope"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="telefone_cadastro">Telefone</label>
                    <div class="control has-icons-left">
                        <input class="input" type="text" id="telefone_atualizar" name="telefone"
                               placeholder="Digite seu telefone" required>
                        <span class="icon is-small is-left">
                            <i class="fas fa-phone"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="button is-primary" type="submit" value="Enviar" id="enviar_atualizar">
                    </div>
                </div>
            </form>
        </div>

        <!-- Formalário para Deletar Cliente -->
        <div class="box">
            <h2 class="title is-4">Deletar</h2>
            <form id="form_deletar" onsubmit="event.preventDefault(); deletarCliente()">
                <div class="field">
                    <label class="label" for="id_deletar">ID</label>
                    <div class="control has-icons-left">
                        <input class="input" type="number" id="id_deletar" name="id" placeholder="Digite o ID" required>
                        <span class="icon is-small is-left">
                            <i class="fas fa-trash-alt"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <button class="button is-danger" type="submit">
                                <span class="icon">
                                    <i class="fas fa-trash-alt"></i>
                                </span>
                            <span>Deletar</span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="{{ url_for('static', filename='cliente.js') }}"></script>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <style>
        body {
            background-color: #f5f5f5;
            min-height: 100vh;
            padding: 1rem;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .box {
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            max-width: 600px;
            margin: 0 auto;
        }
        .title.is-1 {
            color: #3273dc;
        }
        .button.is-primary {
            background-color: #3273dc;
        }
        .buttons {
            flex-wrap: wrap;
        }
        @media screen and (max-width: 768px) {
            .buttons .button {
                margin-bottom: 0.5rem;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="box">
            <h1 class="title is-1 has-text-centered">Bem vindo!!</h1>
            <div class="buttons is-centered">
                <button class="button is-primary is-rounded" onclick="window.location.href='{{ url_for("cliente.index") }}'">
                    <span class="icon">
                        <i class="fas fa-users"></i>
                    </span>
                    <span>Cliente</span>
                </button>
                <button class="button is-primary is-rounded" onclick="window.location.href='{{ url_for("compra.index") }}'">
                    <span class="icon">
                        <i class="fas fa-shopping-cart"></i>
                    </span>
                    <span>Compra</span>
                </button>
                <button class="button is-primary is-rounded" onclick="window.location.href='{{ url_for("produto.index") }}'">
                    <span class="icon">
                        <i class="fas fa-box"></i>
                    </span>
                    <span>Produto</span>
                </button>
            </div>
        </div>
    </div>
</body>
</html>

app/templates/produto_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=devic-width, initial-scale=1.0">
    <title>Gerenciar Produtos</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <style>
        body {
            background-color: #f5f5f5;
            min-height: 100vh;
            padding: 1rem;
        }

        .box {
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            margin-bottom: 2rem;
        }

        .title.is-1 {
            color: #3273dc;
        }

        .table-container {
            overflow-x: auto;
        }

        .button.is-primary {
            background-color: #3273dc;
        }

        .button.is-danger {
            background-color: #ff3860;
        }

        .button.is-info {
            background-color: #23d160;
        }

        .button.is-loading::after {
            border-color: transparent transparent #fff #fff !important;
        }

        @media screen and (max-width: 768px) {
            .columns.is-mobile > .column {
                margin-bottom: 1rem;
            }
        }
    </style>
</head>
<body>
<div class="box">

    <div class="container is-max-desktop">
        <h1 class="title is-1 has-text-centered">Produtos</h1>
        <div class="buttons is-centered">
            <button class="button is-primary is-rounded" onclick="window.location.href='http://127.0.0.1:5000/'">
                    <span class="icon">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                <span>Voltar</span>
            </button>
        </div>

        <!-- Formulário de Cadastro para produtos --->
        <div class="box">
            <form id="form_cadastro">
                <h2 class="title is-4">Cadastrar Produtos</h2>
                <div class="field">
                    <label class="label" for="nome_cadastro">Nome:</label>
                    <div class="control has-icons-left">
                        <input class="input" type="text" id="nome_cadastro" name="nome" placeholder="Produto:" required>
                        <span class="icon is-small is-left">
                                <i class="fas fa-box"></i>
                            </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="descricao_cadastro_cadastro">Descrição:</label>
                    <div class="control has-icons-left">
                        <input class="input" type="text" id="descricao_cadastro" name="descricao"
                               placeholder="Descrição:" required>
                        <span class="icon is-small is-left">
                                <i class="fas fa-info-circle"></i>
                            </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="preco_cadastro">Valor:</label>
                    <div class="control has-icons-left">
                        <input class="input" type="number" id="preco_cadastro" name="preco" placeholder="Valor: "
                               required>
                        <span class="icon is-small is-left">
                                <i class="fas fa-dollar-sign"></i>
                            </span>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="button is-primary is-rounded" type="submit" value="Enviar" id="enviar_cadastro">
                    </div>
                </div>
            </form>
        </div>

        <!-- Tabela para listar produtos --->
        <div class="box">
            <h2 class="title is-4">Listar Produtos</h2>
            <button class="button is-info is-rounded" id="Carregar_btn" onclick="fetchDataProduto()">
                    <span class="icon">
                        <i class="fas fa-list"></i>
                    </span>
                <span>Listar</span>
            </button>
            <button class="button is-light is-rounded" id="voltar_btn" onclick="resetTable()">
                    <span class="icon">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                <span>Voltar</span>
            </button>
            <div id="table_container" class="hidden">
                <table class="table is-striped is-hoverable is-fullwidth" id="data_table">
                    <thead>
                    <tr id="header_row"></tr>
                    </thead>
                    <tbody id="table_body"></tbody>
                </table>
            </div>
        </div>

        <!-- Formulário para Atualizar cadastro de produtos --->
        <div class="box">
            <form id="form_atualizar">
                <h2 class="title is-4">Atualizar Produto</h2>
                <div class="field">
                    <label class="label" for="id_atualizar">ID</label>
                    <div class="control has-icons-left">
                        <input class="input" type="number" id="id_atualizar" name="id" placeholder="Digite o ID"
                               required>
                        <span class="icon is-small is-left">
                            <i class="fas fa-id-badge"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="nome_atualizar">Nome:</label>
                    <div class="control has-icons-left">
                        <input class="input" type="text" id="nome_atualizar" name="nome"
                               placeholder="Digite o nome do produto" required>
                        <span class="icon is-small is-left">
                                <i class="fas fa-box"></i>
                            </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="descricao_atualizar">Descrição:</label>
                    <div class="control has-icons-left">
                        <input class="input" type="text" id="descricao_atualizar" name="descricao"
                               placeholder="Digite a descrição" required>
                        <span class="icon is-small is-left">
                                <i class="fas fa-info-circle"></i>
                            </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="valor_atualizar">Valor:</label>
                    <div class="control has-icons-left">
                        <input class="input" type="number" id="valor_atualizar" name="preco"
                               placeholder="Digite o valor" min="0" step="0.01" required>
                        <span class="icon is-small is-left">
                                <i class="fas fa-dollar-sign"></i>
                            </span>
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <input class="button is-primary is-rounded" type="submit" value="Enviar" id="enviar_atualizar">
                    </div>
                </div>

            </form>
        </div>

        <!-- Formulário para deletar cadastro Produto -->
        <div class="box">
            <h2 class="title is-4">Deletar</h2>
            <form id="form_deletar">
                <div class="field">
                    <label class="label" for="id_deletar">ID:</label>
                    <div class="control has-icons-left">
                        <input class="input" type="number" id="id_deletar" name="id"
                               placeholder="Digite o ID do produto" required>
                        <span class="icon is-small is-left">
                                <i class="fas fa-trash-alt"></i>
                            </span>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <button class="button is-danger is-rounded" type="submit">
                                <span class="icon">
                                    <i class="fas fa-trash-alt"></i>
                                </span>
                            <span>Deletar</span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='produto.js') }}"></script>
</body>
</html>